[package]
name = "morph-core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
blake2b-rs.workspace = true
hex.workspace = true
k256.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
ckb-testtool.workspace = true
morph-script-common = { path = "../../contracts/morph-script-common" }
proptest.workspace = true
serde_json.workspace = true
