[package]
name = "morph-fiber-adapter"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true
publish = false

[dependencies]
hex.workspace = true
morph-core = { version = "1.11.0", path = "../morph-core" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
axum.workspace = true
k256.workspace = true
tokio.workspace = true
