use std::{
    collections::{BTreeMap, BTreeSet},
    fs::{self, File, OpenOptions},
    io::{Read, Write},
    path::{Path, PathBuf},
    sync::Mutex,
};

#[cfg(unix)]
use std::os::unix::fs::OpenOptionsExt;

use rand::{RngCore, rngs::OsRng};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;

use crate::{
    crypto::{AES_GCM_NONCE_LEN, decrypt_with_nonce, encrypt_with_nonce, random_byte32},
    protocol::{FairExchangeEnvelope, PaymentReceipt, PaymentRequirements},
};

const STORE_MAGIC: &[u8; 8] = b"MORPHAG1";
const STORE_SCHEMA_VERSION: u32 = 2;
const MAX_STORE_BYTES: u64 = 64 * 1024 * 1024;

#[derive(Debug, Error)]
pub enum StoreError {
    #[error("agent store I/O failed: {0}")]
    Io(String),
    #[error("agent store is corrupt, has the wrong key, or is too large")]
    Corrupt,
    #[error("agent store schema version is unsupported")]
    UnsupportedVersion,
    #[error("agent store lock is poisoned")]
    LockPoisoned,
    #[error("record already exists with different content")]
    Conflict,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChallengeRecord {
    pub requirement: PaymentRequirements,
    /// Secret generated by Morph and passed to Fiber's `new_invoice`.
    pub payment_preimage: String,
    pub created_at: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StoredOffer {
    pub envelope: FairExchangeEnvelope,
    pub decryption_key: String,
    pub associated_data: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PaymentDirection {
    Incoming,
    Outgoing,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TrackedPayment {
    pub payment_hash: String,
    pub requirement_id: String,
    pub direction: PaymentDirection,
    pub status: String,
    pub updated_at: u64,
    pub fiber_result: Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct PersistedState {
    schema_version: u32,
    challenges: BTreeMap<String, ChallengeRecord>,
    receipts: BTreeMap<String, PaymentReceipt>,
    offers: BTreeMap<String, StoredOffer>,
    payments: BTreeMap<String, TrackedPayment>,
    consumed_requirements: BTreeSet<String>,
}

impl Default for PersistedState {
    fn default() -> Self {
        Self {
            schema_version: STORE_SCHEMA_VERSION,
            challenges: BTreeMap::new(),
            receipts: BTreeMap::new(),
            offers: BTreeMap::new(),
            payments: BTreeMap::new(),
            consumed_requirements: BTreeSet::new(),
        }
    }
}

pub struct DurableStore {
    path: PathBuf,
    key: [u8; 32],
    state: Mutex<PersistedState>,
}

impl DurableStore {
    pub fn open(path: impl Into<PathBuf>, key: [u8; 32]) -> Result<Self, StoreError> {
        let path = path.into();
        let state = if path.exists() {
            read_state(&path, &key)?
        } else {
            PersistedState::default()
        };
        if state.schema_version != STORE_SCHEMA_VERSION {
            return Err(StoreError::UnsupportedVersion);
        }
        let store = Self {
            path,
            key,
            state: Mutex::new(state),
        };
        if !store.path.exists() {
            let initial = store.state.lock().map_err(|_| StoreError::LockPoisoned)?;
            store.persist(&initial)?;
        }
        Ok(store)
    }

    pub fn insert_challenge(&self, record: ChallengeRecord) -> Result<(), StoreError> {
        self.mutate(
            |state| match state.challenges.get(&record.requirement.requirement_id) {
                Some(existing) if existing != &record => Err(StoreError::Conflict),
                Some(_) => Ok(()),
                None => {
                    state
                        .challenges
                        .insert(record.requirement.requirement_id.clone(), record);
                    Ok(())
                }
            },
        )
    }

    pub fn challenge(&self, requirement_id: &str) -> Result<Option<ChallengeRecord>, StoreError> {
        self.read(|state| state.challenges.get(requirement_id).cloned())
    }

    pub fn insert_offer(&self, offer: StoredOffer) -> Result<(), StoreError> {
        self.mutate(|state| match state.offers.get(&offer.envelope.offer_id) {
            Some(existing) if existing != &offer => Err(StoreError::Conflict),
            Some(_) => Ok(()),
            None => {
                state.offers.insert(offer.envelope.offer_id.clone(), offer);
                Ok(())
            }
        })
    }

    pub fn offer(&self, offer_id: &str) -> Result<Option<StoredOffer>, StoreError> {
        self.read(|state| state.offers.get(offer_id).cloned())
    }

    pub fn record_payment(&self, payment: TrackedPayment) -> Result<(), StoreError> {
        self.mutate(|state| {
            state.payments.insert(payment.payment_hash.clone(), payment);
            Ok(())
        })
    }

    pub fn payments(&self, limit: usize) -> Result<Vec<TrackedPayment>, StoreError> {
        self.read(|state| {
            let mut payments = state.payments.values().cloned().collect::<Vec<_>>();
            payments.sort_by(|left, right| {
                right
                    .updated_at
                    .cmp(&left.updated_at)
                    .then_with(|| left.payment_hash.cmp(&right.payment_hash))
            });
            payments.truncate(limit);
            payments
        })
    }

    pub fn receipt(&self, requirement_id: &str) -> Result<Option<PaymentReceipt>, StoreError> {
        self.read(|state| state.receipts.get(requirement_id).cloned())
    }

    pub fn receipt_for_credential(
        &self,
        credential: &str,
    ) -> Result<Option<PaymentReceipt>, StoreError> {
        self.read(|state| {
            state
                .receipts
                .values()
                .find(|receipt| receipt.credential == credential)
                .cloned()
        })
    }

    /// Atomically consumes a challenge and persists its receipt. Concurrent or
    /// retried settles get the first durable receipt rather than a second token.
    pub fn settle_once(&self, receipt: PaymentReceipt) -> Result<PaymentReceipt, StoreError> {
        self.mutate(|state| {
            if let Some(existing) = state.receipts.get(&receipt.requirement_id) {
                return Ok(existing.clone());
            }
            if !state.challenges.contains_key(&receipt.requirement_id) {
                return Err(StoreError::Conflict);
            }
            state
                .consumed_requirements
                .insert(receipt.requirement_id.clone());
            state
                .receipts
                .insert(receipt.requirement_id.clone(), receipt.clone());
            Ok(receipt)
        })
    }

    fn read<T>(&self, f: impl FnOnce(&PersistedState) -> T) -> Result<T, StoreError> {
        let state = self.state.lock().map_err(|_| StoreError::LockPoisoned)?;
        Ok(f(&state))
    }

    fn mutate<T>(
        &self,
        f: impl FnOnce(&mut PersistedState) -> Result<T, StoreError>,
    ) -> Result<T, StoreError> {
        let mut state = self.state.lock().map_err(|_| StoreError::LockPoisoned)?;
        let mut candidate = state.clone();
        let result = f(&mut candidate)?;
        self.persist(&candidate)?;
        *state = candidate;
        Ok(result)
    }

    fn persist(&self, state: &PersistedState) -> Result<(), StoreError> {
        let plaintext = serde_json::to_vec(state).map_err(|_| StoreError::Corrupt)?;
        if plaintext.len() as u64 + STORE_MAGIC.len() as u64 + AES_GCM_NONCE_LEN as u64 + 16
            > MAX_STORE_BYTES
        {
            return Err(StoreError::Corrupt);
        }
        let mut nonce = [0_u8; AES_GCM_NONCE_LEN];
        OsRng.fill_bytes(&mut nonce);
        let ciphertext = encrypt_with_nonce(&self.key, &nonce, &plaintext, STORE_MAGIC)
            .map_err(|_| StoreError::Corrupt)?;

        let parent = self
            .path
            .parent()
            .filter(|path| !path.as_os_str().is_empty());
        if let Some(parent) = parent {
            fs::create_dir_all(parent).map_err(io_error)?;
        }
        let random_suffix = hex::encode(&random_byte32()[..8]);
        let file_name = self
            .path
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or_else(|| StoreError::Io("store path has no valid file name".to_string()))?;
        let temp_path = self
            .path
            .with_file_name(format!(".{file_name}.{random_suffix}.tmp"));
        let mut options = OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        options.mode(0o600);
        let write_result = (|| -> Result<(), StoreError> {
            let mut file = options.open(&temp_path).map_err(io_error)?;
            file.write_all(STORE_MAGIC).map_err(io_error)?;
            file.write_all(&nonce).map_err(io_error)?;
            file.write_all(&ciphertext).map_err(io_error)?;
            file.sync_all().map_err(io_error)?;
            fs::rename(&temp_path, &self.path).map_err(io_error)?;
            if let Some(parent) = parent {
                File::open(parent)
                    .and_then(|dir| dir.sync_all())
                    .map_err(io_error)?;
            }
            Ok(())
        })();
        if write_result.is_err() {
            let _ = fs::remove_file(&temp_path);
        }
        write_result
    }
}

fn read_state(path: &Path, key: &[u8; 32]) -> Result<PersistedState, StoreError> {
    let metadata = fs::metadata(path).map_err(io_error)?;
    let header_len = (STORE_MAGIC.len() + AES_GCM_NONCE_LEN) as u64;
    if metadata.len() <= header_len || metadata.len() > MAX_STORE_BYTES {
        return Err(StoreError::Corrupt);
    }
    let mut bytes = Vec::with_capacity(metadata.len() as usize);
    File::open(path)
        .and_then(|mut file| file.read_to_end(&mut bytes))
        .map_err(io_error)?;
    if bytes.get(..STORE_MAGIC.len()) != Some(STORE_MAGIC) {
        return Err(StoreError::Corrupt);
    }
    let nonce_start = STORE_MAGIC.len();
    let ciphertext_start = nonce_start + AES_GCM_NONCE_LEN;
    let plaintext = decrypt_with_nonce(
        key,
        &bytes[nonce_start..ciphertext_start],
        &bytes[ciphertext_start..],
        STORE_MAGIC,
    )
    .map_err(|_| StoreError::Corrupt)?;
    serde_json::from_slice(&plaintext).map_err(|_| StoreError::Corrupt)
}

fn io_error(error: std::io::Error) -> StoreError {
    StoreError::Io(error.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::{AssetKind, RgbppAsset};

    fn challenge() -> ChallengeRecord {
        ChallengeRecord {
            requirement: PaymentRequirements {
                requirement_id: format!("0x{}", "10".repeat(32)),
                scheme: "exact".to_string(),
                network: "morph-ckb".to_string(),
                payment_rail: "fiber".to_string(),
                asset: RgbppAsset {
                    kind: AssetKind::Ckb,
                    ckb_network_id: format!("0x{}", "01".repeat(32)),
                    type_script_hash: None,
                    type_script: None,
                    bitcoin_network: None,
                    binding_code_hash: None,
                    symbol: "CKB".to_string(),
                    decimals: 8,
                },
                amount: "100".to_string(),
                payer: format!("0x{}", "02".repeat(32)),
                payee: format!("0x{}", "03".repeat(32)),
                invoice: "invoice-secret-marker".to_string(),
                payment_hash: format!("0x{}", "20".repeat(32)),
                hash_algorithm: "sha256".to_string(),
                resource: "/resource".to_string(),
                operation: "GET".to_string(),
                nonce: format!("0x{}", "30".repeat(32)),
                rgbpp_proof_commitment: None,
                expires_at: u64::MAX,
            },
            payment_preimage: format!("0x{}", "40".repeat(32)),
            created_at: 1,
        }
    }

    #[test]
    fn store_is_encrypted_and_survives_restart() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("agent.db");
        let key = [9_u8; 32];
        let record = challenge();
        DurableStore::open(&path, key)
            .unwrap()
            .insert_challenge(record.clone())
            .unwrap();
        let bytes = fs::read(&path).unwrap();
        assert!(
            !bytes
                .windows("invoice-secret-marker".len())
                .any(|window| { window == "invoice-secret-marker".as_bytes() })
        );
        let restored = DurableStore::open(&path, key).unwrap();
        assert_eq!(
            restored
                .challenge(&record.requirement.requirement_id)
                .unwrap(),
            Some(record)
        );
        assert!(matches!(
            DurableStore::open(&path, [8_u8; 32]),
            Err(StoreError::Corrupt)
        ));
    }
}
