use std::{
    collections::{BTreeMap, BTreeSet},
    fs::{self, File, OpenOptions},
    io::{Read, Write},
    path::{Path, PathBuf},
    sync::Mutex,
};

#[cfg(unix)]
use std::os::unix::fs::OpenOptionsExt;

use rand::{RngCore, rngs::OsRng};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;

use crate::{
    crypto::{AES_GCM_NONCE_LEN, decrypt_with_nonce, encrypt_with_nonce, random_byte32},
    protocol::{FairExchangeEnvelope, PaymentReceipt, PaymentRequirements},
};

const STORE_MAGIC: &[u8; 8] = b"MORPHAG1";
const STORE_SCHEMA_VERSION: u32 = 2;
const MAX_STORE_BYTES: u64 = 64 * 1024 * 1024;
const MAX_TRANSIENT_STORE_BYTES: usize = 48 * 1024 * 1024;
const MAX_OUTSTANDING_CHALLENGES: usize = 2_048;
const MAX_STORED_OFFERS: usize = 24;
const MAX_SETTLED_RECEIPTS: usize = 2_048;
const MAX_TRACKED_PAYMENTS: usize = 256;
const MAX_TRACKED_PAYMENT_JSON_BYTES: usize = 64 * 1024;

#[derive(Debug, Error)]
pub enum StoreError {
    #[error("agent store I/O failed: {0}")]
    Io(String),
    #[error("agent store is corrupt, has the wrong key, or is too large")]
    Corrupt,
    #[error("agent store schema version is unsupported")]
    UnsupportedVersion,
    #[error("agent store lock is poisoned")]
    LockPoisoned,
    #[error("record already exists with different content")]
    Conflict,
    #[error("agent store reached a configured record or reserve limit")]
    CapacityExceeded,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ChallengeRecord {
    pub requirement: PaymentRequirements,
    /// Secret generated by Morph and passed to Fiber's `new_invoice`.
    pub payment_preimage: String,
    pub created_at: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StoredOffer {
    pub envelope: FairExchangeEnvelope,
    pub decryption_key: String,
    pub associated_data: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PaymentDirection {
    Incoming,
    Outgoing,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TrackedPayment {
    pub payment_hash: String,
    pub requirement_id: String,
    pub direction: PaymentDirection,
    pub status: String,
    pub updated_at: u64,
    pub fiber_result: Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct PersistedState {
    schema_version: u32,
    challenges: BTreeMap<String, ChallengeRecord>,
    receipts: BTreeMap<String, PaymentReceipt>,
    offers: BTreeMap<String, StoredOffer>,
    payments: BTreeMap<String, TrackedPayment>,
    consumed_requirements: BTreeSet<String>,
}

impl Default for PersistedState {
    fn default() -> Self {
        Self {
            schema_version: STORE_SCHEMA_VERSION,
            challenges: BTreeMap::new(),
            receipts: BTreeMap::new(),
            offers: BTreeMap::new(),
            payments: BTreeMap::new(),
            consumed_requirements: BTreeSet::new(),
        }
    }
}

pub struct DurableStore {
    path: PathBuf,
    key: [u8; 32],
    state: Mutex<PersistedState>,
}

impl DurableStore {
    pub fn open(path: impl Into<PathBuf>, key: [u8; 32]) -> Result<Self, StoreError> {
        let path = path.into();
        let state = if path.exists() {
            read_state(&path, &key)?
        } else {
            PersistedState::default()
        };
        if state.schema_version != STORE_SCHEMA_VERSION {
            return Err(StoreError::UnsupportedVersion);
        }
        let store = Self {
            path,
            key,
            state: Mutex::new(state),
        };
        if !store.path.exists() {
            let initial = store.state.lock().map_err(|_| StoreError::LockPoisoned)?;
            store.persist(&initial)?;
        }
        Ok(store)
    }

    pub fn insert_challenge(&self, record: ChallengeRecord) -> Result<(), StoreError> {
        self.mutate(|state| {
            prune_expired_transient_records(state, record.created_at);
            match state.challenges.get(&record.requirement.requirement_id) {
                Some(existing) if existing != &record => Err(StoreError::Conflict),
                Some(_) => Ok(()),
                None => {
                    let outstanding = state
                        .challenges
                        .keys()
                        .filter(|requirement_id| !state.receipts.contains_key(*requirement_id))
                        .count();
                    if outstanding >= MAX_OUTSTANDING_CHALLENGES {
                        return Err(StoreError::CapacityExceeded);
                    }
                    state
                        .challenges
                        .insert(record.requirement.requirement_id.clone(), record);
                    ensure_transient_reserve(state)?;
                    Ok(())
                }
            }
        })
    }

    pub fn challenge(&self, requirement_id: &str) -> Result<Option<ChallengeRecord>, StoreError> {
        self.read(|state| state.challenges.get(requirement_id).cloned())
    }

    pub fn insert_offer(&self, offer: StoredOffer) -> Result<(), StoreError> {
        self.mutate(|state| {
            prune_expired_transient_records(state, unix_time_seconds());
            match state.offers.get(&offer.envelope.offer_id) {
                Some(existing) if existing != &offer => Err(StoreError::Conflict),
                Some(_) => Ok(()),
                None => {
                    if state.offers.len() >= MAX_STORED_OFFERS {
                        return Err(StoreError::CapacityExceeded);
                    }
                    state.offers.insert(offer.envelope.offer_id.clone(), offer);
                    ensure_transient_reserve(state)?;
                    Ok(())
                }
            }
        })
    }

    pub fn offer(&self, offer_id: &str) -> Result<Option<StoredOffer>, StoreError> {
        self.read(|state| state.offers.get(offer_id).cloned())
    }

    pub fn record_payment(&self, payment: TrackedPayment) -> Result<(), StoreError> {
        if serde_json::to_vec(&payment.fiber_result)
            .map_err(|_| StoreError::Corrupt)?
            .len()
            > MAX_TRACKED_PAYMENT_JSON_BYTES
        {
            return Err(StoreError::CapacityExceeded);
        }
        self.mutate(|state| {
            state.payments.insert(payment.payment_hash.clone(), payment);
            while state.payments.len() > MAX_TRACKED_PAYMENTS {
                let oldest = state
                    .payments
                    .iter()
                    .min_by(|left, right| {
                        left.1
                            .updated_at
                            .cmp(&right.1.updated_at)
                            .then_with(|| left.0.cmp(right.0))
                    })
                    .map(|(payment_hash, _)| payment_hash.clone())
                    .ok_or(StoreError::Corrupt)?;
                state.payments.remove(&oldest);
            }
            ensure_transient_reserve(state)?;
            Ok(())
        })
    }

    pub fn payments(&self, limit: usize) -> Result<Vec<TrackedPayment>, StoreError> {
        self.read(|state| {
            let mut payments = state.payments.values().cloned().collect::<Vec<_>>();
            payments.sort_by(|left, right| {
                right
                    .updated_at
                    .cmp(&left.updated_at)
                    .then_with(|| left.payment_hash.cmp(&right.payment_hash))
            });
            payments.truncate(limit);
            payments
        })
    }

    pub fn receipt(&self, requirement_id: &str) -> Result<Option<PaymentReceipt>, StoreError> {
        self.read(|state| state.receipts.get(requirement_id).cloned())
    }

    pub fn receipt_for_credential(
        &self,
        credential: &str,
    ) -> Result<Option<PaymentReceipt>, StoreError> {
        self.read(|state| {
            state
                .receipts
                .values()
                .find(|receipt| receipt.credential == credential)
                .cloned()
        })
    }

    /// Atomically consumes a challenge and persists its receipt. Concurrent or
    /// retried settles get the first durable receipt rather than a second token.
    pub fn settle_once(&self, receipt: PaymentReceipt) -> Result<PaymentReceipt, StoreError> {
        self.mutate(|state| {
            if let Some(existing) = state.receipts.get(&receipt.requirement_id) {
                return Ok(existing.clone());
            }
            if !state.challenges.contains_key(&receipt.requirement_id) {
                return Err(StoreError::Conflict);
            }
            if state.receipts.len() >= MAX_SETTLED_RECEIPTS {
                return Err(StoreError::CapacityExceeded);
            }
            state
                .consumed_requirements
                .insert(receipt.requirement_id.clone());
            state
                .receipts
                .insert(receipt.requirement_id.clone(), receipt.clone());
            Ok(receipt)
        })
    }

    fn read<T>(&self, f: impl FnOnce(&PersistedState) -> T) -> Result<T, StoreError> {
        let state = self.state.lock().map_err(|_| StoreError::LockPoisoned)?;
        Ok(f(&state))
    }

    fn mutate<T>(
        &self,
        f: impl FnOnce(&mut PersistedState) -> Result<T, StoreError>,
    ) -> Result<T, StoreError> {
        let mut state = self.state.lock().map_err(|_| StoreError::LockPoisoned)?;
        let mut candidate = state.clone();
        let result = f(&mut candidate)?;
        self.persist(&candidate)?;
        *state = candidate;
        Ok(result)
    }

    fn persist(&self, state: &PersistedState) -> Result<(), StoreError> {
        let plaintext = serde_json::to_vec(state).map_err(|_| StoreError::Corrupt)?;
        if plaintext.len() as u64 + STORE_MAGIC.len() as u64 + AES_GCM_NONCE_LEN as u64 + 16
            > MAX_STORE_BYTES
        {
            return Err(StoreError::Corrupt);
        }
        let mut nonce = [0_u8; AES_GCM_NONCE_LEN];
        OsRng.fill_bytes(&mut nonce);
        let ciphertext = encrypt_with_nonce(&self.key, &nonce, &plaintext, STORE_MAGIC)
            .map_err(|_| StoreError::Corrupt)?;

        let parent = self
            .path
            .parent()
            .filter(|path| !path.as_os_str().is_empty());
        if let Some(parent) = parent {
            fs::create_dir_all(parent).map_err(io_error)?;
        }
        let random_suffix = hex::encode(&random_byte32()[..8]);
        let file_name = self
            .path
            .file_name()
            .and_then(|name| name.to_str())
            .ok_or_else(|| StoreError::Io("store path has no valid file name".to_string()))?;
        let temp_path = self
            .path
            .with_file_name(format!(".{file_name}.{random_suffix}.tmp"));
        let mut options = OpenOptions::new();
        options.write(true).create_new(true);
        #[cfg(unix)]
        options.mode(0o600);
        let write_result = (|| -> Result<(), StoreError> {
            let mut file = options.open(&temp_path).map_err(io_error)?;
            file.write_all(STORE_MAGIC).map_err(io_error)?;
            file.write_all(&nonce).map_err(io_error)?;
            file.write_all(&ciphertext).map_err(io_error)?;
            file.sync_all().map_err(io_error)?;
            fs::rename(&temp_path, &self.path).map_err(io_error)?;
            if let Some(parent) = parent {
                File::open(parent)
                    .and_then(|dir| dir.sync_all())
                    .map_err(io_error)?;
            }
            Ok(())
        })();
        if write_result.is_err() {
            let _ = fs::remove_file(&temp_path);
        }
        write_result
    }
}

fn prune_expired_transient_records(state: &mut PersistedState, now: u64) {
    state.challenges.retain(|requirement_id, challenge| {
        challenge.requirement.expires_at > now || state.receipts.contains_key(requirement_id)
    });
    let receipts = &state.receipts;
    state.offers.retain(|_, offer| {
        let credential_expires_at = receipts
            .get(&offer.envelope.requirement.requirement_id)
            .map(|receipt| receipt.credential_expires_at);
        transient_offer_is_live(
            offer.envelope.requirement.expires_at,
            credential_expires_at,
            now,
        )
    });
    state
        .consumed_requirements
        .retain(|requirement_id| state.receipts.contains_key(requirement_id));
}

fn transient_offer_is_live(
    requirement_expires_at: u64,
    credential_expires_at: Option<u64>,
    now: u64,
) -> bool {
    requirement_expires_at > now || credential_expires_at.is_some_and(|expiry| expiry > now)
}

fn ensure_transient_reserve(state: &PersistedState) -> Result<(), StoreError> {
    let length = serde_json::to_vec(state)
        .map_err(|_| StoreError::Corrupt)?
        .len();
    if length > MAX_TRANSIENT_STORE_BYTES {
        Err(StoreError::CapacityExceeded)
    } else {
        Ok(())
    }
}

fn unix_time_seconds() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |duration| duration.as_secs())
}

fn read_state(path: &Path, key: &[u8; 32]) -> Result<PersistedState, StoreError> {
    let metadata = fs::metadata(path).map_err(io_error)?;
    let header_len = (STORE_MAGIC.len() + AES_GCM_NONCE_LEN) as u64;
    if metadata.len() <= header_len || metadata.len() > MAX_STORE_BYTES {
        return Err(StoreError::Corrupt);
    }
    let mut bytes = Vec::with_capacity(metadata.len() as usize);
    File::open(path)
        .and_then(|mut file| file.read_to_end(&mut bytes))
        .map_err(io_error)?;
    if bytes.get(..STORE_MAGIC.len()) != Some(STORE_MAGIC) {
        return Err(StoreError::Corrupt);
    }
    let nonce_start = STORE_MAGIC.len();
    let ciphertext_start = nonce_start + AES_GCM_NONCE_LEN;
    let plaintext = decrypt_with_nonce(
        key,
        &bytes[nonce_start..ciphertext_start],
        &bytes[ciphertext_start..],
        STORE_MAGIC,
    )
    .map_err(|_| StoreError::Corrupt)?;
    serde_json::from_slice(&plaintext).map_err(|_| StoreError::Corrupt)
}

fn io_error(error: std::io::Error) -> StoreError {
    StoreError::Io(error.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protocol::{AssetKind, RgbppAsset};

    fn challenge() -> ChallengeRecord {
        ChallengeRecord {
            requirement: PaymentRequirements {
                requirement_id: format!("0x{}", "10".repeat(32)),
                scheme: "exact".to_string(),
                network: "morph-ckb".to_string(),
                payment_rail: "fiber".to_string(),
                asset: RgbppAsset {
                    kind: AssetKind::Ckb,
                    ckb_network_id: format!("0x{}", "01".repeat(32)),
                    type_script_hash: None,
                    type_script: None,
                    bitcoin_network: None,
                    binding_code_hash: None,
                    symbol: "CKB".to_string(),
                    decimals: 8,
                },
                amount: "100".to_string(),
                payer: format!("0x{}", "02".repeat(32)),
                payee: format!("0x{}", "03".repeat(32)),
                invoice: "invoice-secret-marker".to_string(),
                payment_hash: format!("0x{}", "20".repeat(32)),
                hash_algorithm: "sha256".to_string(),
                resource: "/resource".to_string(),
                operation: "GET".to_string(),
                nonce: format!("0x{}", "30".repeat(32)),
                rgbpp_proof_commitment: None,
                expires_at: u64::MAX,
            },
            payment_preimage: format!("0x{}", "40".repeat(32)),
            created_at: 1,
        }
    }

    fn challenge_with_tag(tag: u64, created_at: u64, expires_at: u64) -> ChallengeRecord {
        let mut record = challenge();
        record.requirement.requirement_id = format!("0x{tag:064x}");
        record.requirement.payment_hash = format!("0x{:064x}", tag + 1);
        record.requirement.nonce = format!("0x{:064x}", tag + 2);
        record.requirement.expires_at = expires_at;
        record.created_at = created_at;
        record
    }

    #[test]
    fn store_is_encrypted_and_survives_restart() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("agent.db");
        let key = [9_u8; 32];
        let record = challenge();
        DurableStore::open(&path, key)
            .unwrap()
            .insert_challenge(record.clone())
            .unwrap();
        let bytes = fs::read(&path).unwrap();
        assert!(
            !bytes
                .windows("invoice-secret-marker".len())
                .any(|window| { window == "invoice-secret-marker".as_bytes() })
        );
        let restored = DurableStore::open(&path, key).unwrap();
        assert_eq!(
            restored
                .challenge(&record.requirement.requirement_id)
                .unwrap(),
            Some(record)
        );
        assert!(matches!(
            DurableStore::open(&path, [8_u8; 32]),
            Err(StoreError::Corrupt)
        ));
    }

    #[test]
    fn expired_transient_records_are_pruned_before_capacity_checks() {
        let dir = tempfile::tempdir().unwrap();
        let store = DurableStore::open(dir.path().join("agent.db"), [9_u8; 32]).unwrap();
        let expired = challenge_with_tag(1, 10, 20);
        store.insert_challenge(expired.clone()).unwrap();
        store
            .insert_challenge(challenge_with_tag(2, 21, u64::MAX))
            .unwrap();
        assert!(
            store
                .challenge(&expired.requirement.requirement_id)
                .unwrap()
                .is_none()
        );
    }

    #[test]
    fn settled_offer_retention_ends_with_its_credential() {
        assert!(transient_offer_is_live(20, Some(40), 30));
        assert!(!transient_offer_is_live(20, Some(30), 30));
        assert!(!transient_offer_is_live(20, None, 30));
    }

    #[test]
    fn outstanding_challenge_quota_rejects_without_corrupting_existing_state() {
        let dir = tempfile::tempdir().unwrap();
        let store = DurableStore::open(dir.path().join("agent.db"), [9_u8; 32]).unwrap();
        store
            .mutate(|state| {
                for tag in 0..MAX_OUTSTANDING_CHALLENGES as u64 {
                    let record = challenge_with_tag(tag, 1, u64::MAX);
                    state
                        .challenges
                        .insert(record.requirement.requirement_id.clone(), record);
                }
                Ok(())
            })
            .unwrap();
        let rejected = challenge_with_tag(MAX_OUTSTANDING_CHALLENGES as u64 + 10, 1, u64::MAX);
        assert!(matches!(
            store.insert_challenge(rejected.clone()),
            Err(StoreError::CapacityExceeded)
        ));
        assert!(
            store
                .challenge(&rejected.requirement.requirement_id)
                .unwrap()
                .is_none()
        );
        assert!(store.challenge(&format!("0x{:064x}", 0)).unwrap().is_some());
    }

    #[test]
    fn oversized_raw_payment_metadata_is_not_persisted() {
        let dir = tempfile::tempdir().unwrap();
        let store = DurableStore::open(dir.path().join("agent.db"), [9_u8; 32]).unwrap();
        let result = store.record_payment(TrackedPayment {
            payment_hash: format!("0x{}", "12".repeat(32)),
            requirement_id: format!("0x{}", "13".repeat(32)),
            direction: PaymentDirection::Incoming,
            status: "Paid".to_string(),
            updated_at: 1,
            fiber_result: serde_json::json!({
                "oversized": "x".repeat(MAX_TRACKED_PAYMENT_JSON_BYTES)
            }),
        });
        assert!(matches!(result, Err(StoreError::CapacityExceeded)));
        assert!(store.payments(10).unwrap().is_empty());
    }
}
