[package]
name = "morph-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true
publish = false

[features]
default = []
devnet = []

[dependencies]
anyhow.workspace = true
ckb-crypto.workspace = true
ckb-hash.workspace = true
ckb-jsonrpc-types.workspace = true
ckb-types.workspace = true
clap.workspace = true
getrandom.workspace = true
hex.workspace = true
k256.workspace = true
morph-core = { version = "2.0.0", path = "../morph-core" }
morph-script-common = { version = "0.1.0", path = "../../contracts/morph-script-common" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
url = "2.5"
