[package]
name = "morph-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
ckb-crypto.workspace = true
ckb-hash.workspace = true
ckb-jsonrpc-types.workspace = true
ckb-types.workspace = true
clap.workspace = true
hex.workspace = true
k256.workspace = true
morph-core = { path = "../morph-core" }
morph-script-common = { path = "../../contracts/morph-script-common" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10"
url = "2.5"
